### ISSUE TITLE
Pobieranie danych od użytkownika oraz ich jednoczesne "setowanie"

### ISSUE THREAD

**Issue by IgorKalinowskii** [KNJPJATK/SOBOTA_POCZ#1]
<img width="1280" alt="zrzut ekranu 2016-10-31 o 20 47 16" src="https://cloud.githubusercontent.com/assets/23176474/19869122/3ca49722-9fab-11e6-94da-5d7b1d8641f8.png">

Witam,
czy jest możliwość aby wpisana przez użytkownika wartość mogła od razu wskoczyć do "seta"? Czyli gdy wpiszę w konsoli: 5, dostane informację zwrotną o tym, że mam 5 banknotów o wartości 50 zł.
Proszę o pomoc.

**Comment by procek69** [comment]
Scanner i czytanie per linia i parsowanie jest dość niebezpiecznie:

`Scanner s = new Scanner(System.in);
if (s.hasNextInt()) {
    int x = s.nextInt();
}`

**Comment by procek69** [comment]
PS: na macu może Pan użyć CMD+Shift+4, to wtedy zrobi Pan screena z zaznaczonego ekranu
